# Generated by Django 4.2.9 on 2024-03-16 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_user',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
